name: Security Checks
on:
  pull_request:
  push:

jobs:
    semgrep:
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep:latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Run Semgrep
              env:
                SEMGREP_RULES: >-
                  p/security-audit
                  p/owasp-top-ten
                  p/javascript
                  p/python
              run: semgrep ci
    # TODO: Fix Bandit Vulns
    "Bandit":
      runs-on: ubuntu-latest
      container: python:3.11
  
      steps:
        - uses: actions/checkout@v2
  
        - name: Bandit check
          uses: jpetrucciani/bandit-check@master
          with:
            path: "app.py"
            bandit_flags: "-lll"

    "Black":
      runs-on: ubuntu-latest
      container: python:3.11
  
      steps:
        - uses: actions/checkout@v2
  
        - name: Install dependencies
          run: pip install black

        - name: Run black check
          run: black --check .
